apiVersion: apps/v1
kind: Deployment
metadata:
  name: pib-go-deployment
spec:
  replicas: 2  # number of pods
  selector:
    matchLabels:
      app: pib-go
  template:
    metadata:
      labels:
        app: pib-go
    spec:
      containers:
        - name: pib-go
          image: go-orm-app:latest
          imagePullPolicy: IfNotPresent  # pull local image
          env:
            - name: DB_HOST
              value: godb-service  # ClusterIP service name from database

            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DB_NAME
          ports:
            - containerPort: 8080

          # limit resource
          resources:
            limits:
              memory: "128Mi" # Ram
              cpu: "500m" # Cores

---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: LoadBalancer  # จะลองใช้ LoadBalancer แทน NodePort
  selector:
    app: pib-go
  ports:
    - port: 8000         # Port ที่จะเปิดให้เข้าถึงจากข้างนอก
      targetPort: 8080   # Port ที่ container ใช้รับ traffic / port ที่โปรแกรมใช้
      # nodePort: 30003    # NodePort ใช้ไม่ได้เพราะ LoadBalancer เปิด port ออกข้างนอกอยู่แล้ว