apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pib-godb-statefulset
spec:
  serviceName: godb-service
  replicas: 2
  selector:
    matchLabels:
      app: pib-godb
  template:
    metadata:
      labels:
        app: pib-godb
    spec:
      containers:
      - name: pib-godb
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: env
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: env
                key: DB_NAME
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: env
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: env
                key: DB_PASSWORD
        ports:
          - containerPort: 3306
          
        volumeMounts:
          - name: mysql-go-app-storage
            mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-go-app-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi


---
apiVersion: v1
kind: Service
metadata:
  name: godb-service
spec:
  type: ClusterIP
  selector:
    app: pib-godb 
  ports:
    - port: 3306   
      targetPort: 3306
