apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: get-start-go
  template:
    metadata:
      labels:
        app: get-start-go
    spec:
      containers:
        - name: pib-go
          image: pib21/firstgo-app:latest

---
apiVersion: v1
kind: Service
metadata:
  name: service-go
spec:
  type: NodePort
  selector: 
    app: get-start-go   # matchLabels in deployment
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005 