apiVersion: v1
kind: Service 
metadata:
  name: go-serveice
spec:
  type: NodePort
  selector:
    app: pib-go  # matchLabels in deployment
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003   # external port


